### ISSUE TITLE
gr-adapt error (GR-adapt master / GR3.9 PPA)

### ISSUE THREAD

**Issue by woongjae-yoo** [karel/gr-adapt#11]
Hello, here is question again.

Recently, after GR-3.9 PPA minor update, 
GR-adapt has new problem at runtime.

message is as below.

<div class="colorscripter-code" style="color:#010101;font-family:Consolas, 'Liberation Mono', Menlo, Courier, monospace !important; position:relative !important;overflow:auto"><table class="colorscripter-code-table" style="margin:0;padding:0;border:none;background-color:#fafafa;border-radius:4px;" cellspacing="0" cellpadding="0"><tr><td style="padding:6px;border-right:2px solid #e5e5e5"><div style="margin:0;padding:0;word-break:normal;text-align:right;color:#666;font-family:Consolas, 'Liberation Mono', Menlo, Courier, monospace !important;line-height:130%"><div style="line-height:130%">1</div><div style="line-height:130%">2</div><div style="line-height:130%">3</div><div style="line-height:130%">4</div><div style="line-height:130%">5</div><div style="line-height:130%">6</div><div style="line-height:130%">7</div><div style="line-height:130%">8</div></div></td><td style="padding:6px 0;text-align:left"><div style="margin:0;padding:0;color:#010101;font-family:Consolas, 'Liberation Mono', Menlo, Courier, monospace !important;line-height:130%"><div style="padding:0 6px; white-space:pre; line-height:130%">Traceback&nbsp;(most&nbsp;recent&nbsp;call&nbsp;last):</div><div style="padding:0 6px; white-space:pre; line-height:130%">&nbsp;&nbsp;File&nbsp;<span style="color:#63a35c">"/home/woongjaeyoo/gr-adapt-maint-3.9/examples/self_interference_cancellation.py"</span>,&nbsp;line&nbsp;<span style="color:#0099cc">41</span>,&nbsp;<span style="color:#a71d5d">in</span>&nbsp;<span style="color:#0086b3"></span><span style="color:#a71d5d">&lt;</span>module<span style="color:#0086b3"></span><span style="color:#a71d5d">&gt;</span></div><div style="padding:0 6px; white-space:pre; line-height:130%">&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:#a71d5d">import</span>&nbsp;adapt</div><div style="padding:0 6px; white-space:pre; line-height:130%">&nbsp;&nbsp;File&nbsp;<span style="color:#63a35c">"/usr/lib/python3/dist-packages/adapt/__init__.py"</span>,&nbsp;line&nbsp;<span style="color:#0099cc">22</span>,&nbsp;<span style="color:#a71d5d">in</span>&nbsp;<span style="color:#0086b3"></span><span style="color:#a71d5d">&lt;</span>module<span style="color:#0086b3"></span><span style="color:#a71d5d">&gt;</span></div><div style="padding:0 6px; white-space:pre; line-height:130%">&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:#a71d5d">from</span>&nbsp;.adapt_python&nbsp;<span style="color:#a71d5d">import</span>&nbsp;<span style="color:#0086b3"></span><span style="color:#a71d5d">*</span></div><div style="padding:0 6px; white-space:pre; line-height:130%">ImportError:&nbsp;generic_type:&nbsp;type&nbsp;<span style="color:#63a35c">"lms_filter_ff"</span>&nbsp;referenced&nbsp;unknown&nbsp;base&nbsp;type&nbsp;<span style="color:#63a35c">"gr::sync_decimator"</span></div><div style="padding:0 6px; white-space:pre; line-height:130%">&nbsp;</div><div style="padding:0 6px; white-space:pre; line-height:130%"><span style="color:#0086b3"></span><span style="color:#a71d5d">&gt;</span><span style="color:#0086b3"></span><span style="color:#a71d5d">&gt;</span><span style="color:#0086b3"></span><span style="color:#a71d5d">&gt;</span>&nbsp;Done&nbsp;(<span style="color:#a71d5d">return</span>&nbsp;code&nbsp;<span style="color:#0099cc">1</span>)</div></div><div style="text-align:right;margin-top:-13px;margin-right:5px;font-size:9px;font-style:italic"><a href="http://colorscripter.com/info#e" target="_blank" style="color:#e5e5e5text-decoration:none">Colored by Color Scripter</a></div></td><td style="vertical-align:bottom;padding:0 2px 4px 0"><a href="http://colorscripter.com/info#e" target="_blank" style="text-decoration:none;color:white"><span style="font-size:9px;word-break:normal;background-color:#e5e5e5;color:white;border-radius:10px;padding:1px">cs</span></a></td></tr></table></div>

is there any solution for this error?

the gr-adapt worked well before GR-3.9.4.0 update until November 2021 in my Ubuntu PC.

thank you.

**Comment by karel** [comment]
After updating GNU Radio, try rebuilding gr-adapt from scratch. The `maint-3.9` branch of gr-adapt had been lagging and missing the commit 573c1281efa07c6f94d10a268920f9ad2334f845, but the branch is updated now. Currently, both `maint-3.9` and `master` branches seem to work against GNU Radio `maint-3.9` and I am unable to reproduce the runtime error you are reporting.
