### ISSUE TITLE
AttributeError: module 'adapt' has no attribute 'lms_filter_ff' v3.8

### ISSUE THREAD

**Issue by Caglarr** [karel/gr-adapt#13]
Dear Karel,

I am using DragonOS operating system. This system uses Gnu Radio v3.8.1.0 (Python 3.8.10). After pulling your maint3-8 branch, I installed it with all its dependencies. But I am getting lms_filter_ff error. Is there anything you think I'm missing?

The error is like shown below, and I'm trying to use example project which is adaptive_line_enhancer.

```
Generating: '/home/caglar/gr-adapt-maint-3.8/examples/adaptive_line_enhancer.py'

Executing: /usr/bin/python3 -u /home/caglar/gr-adapt-maint-3.8/examples/adaptive_line_enhancer.py

Traceback (most recent call last):
  File "/home/caglar/gr-adapt-maint-3.8/examples/adaptive_line_enhancer.py", line 356, in <module>
    main()
  File "/home/caglar/gr-adapt-maint-3.8/examples/adaptive_line_enhancer.py", line 334, in main
    tb = top_block_cls()
  File "/home/caglar/gr-adapt-maint-3.8/examples/adaptive_line_enhancer.py", line 240, in __init__
    self.adapt_lms_filter_xx_0 = adapt.lms_filter_ff(True, n_taps, gui_lms_mu, 0, 1, gui_adapt, False, gui_reset)
AttributeError: module 'adapt' has no attribute 'lms_filter_ff'

>>> Done (return code 1)

```

Being able to use these filters is very important to me right now.

Thank you for your patience and help.

Best Regards.

**Comment by karel** [comment]
Run `sudo ldconfig` after the commands in [readme](https://github.com/karel/gr-adapt#building-from-source).

**Comment by Caglarr** [comment]
Thanks. It's working now.
