### ISSUE TITLE
Brief overview of the developed project

### ISSUE THREAD

**Issue by Caglarr** [karel/gr-adapt#14]
Dear Karel,

I would like to get an opinion from an experienced glance about the blog diagrams I have developed. maybe I can get a better result in my project with your experience. I didn't know how to reach it. I thought of writing here. If possible, do you have an e-mail address where I can reach you? or I can share my email address.

Best Regards.

**Comment by karel** [comment]
Hi Caglar, the best way to get feedback about GNU Radio projects is to either join the [GNU Radio chat room](https://chat.gnuradio.org) or write to the [GNU Radio mailing list](https://wiki.gnuradio.org/index.php/MailingLists). I try to keep an eye on those channels.
