### ISSUE TITLE
Errors While Running CTest

### ISSUE THREAD

**Issue by Caglarr** [karel/gr-adapt#15]
Dear Karel,

Hope you are doing well. I'm grateful for your help on previous issues. I ran into a problem. A few tests that I run under build/python in the 3.8 branch are successful and I can see the signal and error graphs as the screen output. Unfortunately I was unable to run a few tests. An error occurred.

Working tests,

- qa_lms_filter_ff
- qa_nlms_filter_ff
- qa_qrd_rls_filter_ff (test is passed however output gui doesn't appear.)
- qa_iqrd_rls_filter_ff

Not working tests,

- qa_rls_filter_ff
- qa_convergence_ff

Thanks in advance.

**Comment by Caglarr** [comment]
Dear Karel, Imho I found error regarding convergence test.

Error seems that the casting error.
![image](https://user-images.githubusercontent.com/33661779/203639507-535c0de5-c259-4ffa-af43-c07dae761df1.png)

![image](https://user-images.githubusercontent.com/33661779/203639210-00c4472a-1175-402d-95d5-66258de79601.png)

Now I'm trying to workaround solution. 

If you have any idea please send a message.

Best Regards.

**Comment by Caglarr** [comment]
I solved the problem. Thanks

**Comment by karel** [comment]
Great! Sorry I didn't have time to take a look into this yet. Can you please leave a comment, what was the solution?
