### ISSUE TITLE
Add a noise source to self-interference cancellation example

### ISSUE THREAD

**Issue by andrehoracio97** [karel/gr-adapt#4]
Hi, first of all great job that you have done there, I have a question and this was the only way I have found to do it.  I want do self-interference cancellation only with the knowledge of the Gaussian Noise and the Original signal mixed with that noise. So I pick up your example of self-interference cancellation, and I did this, however it's not working, can you help me please? 

NOTE: After I got that working I need to integrate with QPSK modulation, so I need to recover the right signal without this noise (I already tried Band Pass Filter, but it not recovers well, it's something that I am doing wrong).
 

[self_interference_cancellation_with_gaussian_noise.zip](https://github.com/karel/gr-adapt/files/3686574/self_interference_cancellation_with_gaussian_noise.zip)

**Comment by karel** [comment]
This is a good idea for improving the example. How about the example below? If you don't want the second signal (2 kHz) then set its amplitude to 0.

[self_interference_cancellation.zip](https://github.com/karel/gr-adapt/files/3686733/self_interference_cancellation.zip)

**Comment by andrehoracio97** [comment]
Thanks a lot for answer me. 
In that example, the LMS Filter has knowledge of the original signal (Source Signal with freq 1k). 
What I am talking is when the LMS has no knowledge of the original signal (only the noise added), explaining beter: The LMS only receives the noise, and the signal mixed (of that noise with the original signal). And what I want is recover the original signal.

**Comment by karel** [comment]
Have a look at the [adaptive line enhancer example](https://github.com/karel/gr-adapt/blob/master/examples/adaptive_line_enhancer.grc) then.

![latest-screenshot](https://user-images.githubusercontent.com/5636152/66290888-1642a080-e8e9-11e9-8f78-826aa34820c7.png)

**Comment by andrehoracio97** [comment]
Thanks for helping me, however I still think you didn't understood what I am talking. I have manually draw a block scheme so you can understand better.

Again, Thanks so much for helping me. 
![scheme](https://user-images.githubusercontent.com/32906276/66318040-80bc0680-e912-11e9-8ebb-2a40261d9525.jpg)

**Comment by andrehoracio97** [comment]
Ok, I think I get it. Setting the "First input" as "Reference" in parameters, and If I put the mixed signal in first input of the LMS Filter, and the noise on the second input, then the error output will be my original signal without noise. I am right? 
Just a question: At the input of the LMS Filter Block, the noise sample needs to be inputed at same time as the same noise sample mixed with the original signal?

Thanks for the help ;)
