### ISSUE TITLE
AttributeError: module 'adapt' has no attribute 'lms_filter_ff'

### ISSUE THREAD

**Issue by fhchl** [karel/gr-adapt#6]
I just tried to install this extension, but I am getting an error when using any of the adaptive filter blocks:

```
Traceback (most recent call last):
  File "/home/fmheu/Dropbox/projects/gnuradio/asd.py", line 285, in <module>
    main()
  File "/home/fmheu/Dropbox/projects/gnuradio/asd.py", line 261, in main
    tb = top_block_cls()
  File "/home/fmheu/Dropbox/projects/gnuradio/asd.py", line 220, in __init__
    self.adapt_lms_filter_xx_0 = adapt.lms_filter_ff(True, 256, 0.00001, 0, 1, True, False, False)
AttributeError: module 'adapt' has no attribute 'lms_filter_ff'
```

I installed gnu radio via the ppa at ppa:gnuradio/gnuradio-master and followed the build instructions for gr-adapt in the README with 
```
cmake -DCMAKE_INSTALL_PREFIX=/usr ..  
```
because
``` 
$ gnuradio-config-info --prefix
--> /usr
```
I also installed VOLK with the same prefix. 

The cmake command above says
```
> cmake -DCMAKE_INSTALL_PREFIX=/usr ..                                                                                 master
-- The CXX compiler identification is GNU 9.2.1
-- The C compiler identification is GNU 9.2.1
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Build type not specified: defaulting to release.
-- Found LOG4CPP: /usr/lib/x86_64-linux-gnu/liblog4cpp.so
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Checking for module 'gmp'
--   No package 'gmp' found
-- Found GMP: /usr/lib/x86_64-linux-gnu/libgmpxx.so  
-- Checking for module 'mpir >= 3.0'
--   No package 'mpir' found
-- Could NOT find MPIR (missing: MPIRXX_LIBRARY MPIR_LIBRARY MPIR_INCLUDE_DIR) 
-- Found MPLIB: /usr/lib/x86_64-linux-gnu/libgmpxx.so  
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Boost version: 1.67.0
-- Found the following Boost libraries:
--   date_time
--   program_options
--   filesystem
--   system
--   regex
--   thread
--   unit_test_framework
--   chrono
--   atomic
-- Found VOLK: Volk::volk  
-- User set python executable /usr/bin/python3
-- Found PythonInterp: /usr/bin/python3 (found version "3.7.5") 
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.7m.so (found suitable exact version "3.7.5") 
-- Checking for module 'fftw3f >= 3.0'
--   Found fftw3f , version 3.3.8
-- Found FFTW3f: /usr/lib/x86_64-linux-gnu/libfftw3f.so  
-- Found Git: /usr/bin/git  
-- Extracting version information from git describe...
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) 
-- Looking for sgemm_
-- Looking for sgemm_ - not found
-- Looking for sgemm_
-- Looking for sgemm_ - found
-- Found BLAS: /usr/lib/x86_64-linux-gnu/libblas.so  
-- Looking for cheev_
-- Looking for cheev_ - found
-- A library with LAPACK API found.
-- Found Armadillo: /usr/lib/libarmadillo.so (found version "9.600.5") 
-- Using install prefix: /usr
-- Building for version: 8d92eea6 / 0.1.0git
-- No C++ unit tests... skipping
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) 
-- Could NOT find SWIG (missing: SWIG_EXECUTABLE SWIG_DIR) 
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.7m.so (found version "3.7.5") 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/fmheu/git/gr-adapt/build
```

**Comment by karel** [comment]
Some changes were recently made to the GNU Radio master branch that broke all out-of-tree modules.
https://lists.gnu.org/archive/html/discuss-gnuradio/2020-06/msg00203.html

I will migrate gr-adapt as soon as possible (most likely today). In the meantime, using `ppa:gnuradio/gnuradio-releases` with gr-adapt branch `maint-3.8` should work.

**Comment by fhchl** [comment]
Thanks for the quick answer. I followed your advice, but the error seems to persist. Additionally installing `swig` using `apt` and rebuilding solved the problem! Maybe add to the README that `swig` is a necessary dependency?

**Comment by karel** [comment]
I am glad you got it to work. And it seems like a good idea to mention swig (pybind11 in master) in the dependencies. bb7f0dbbab88c3928eda8fc7e396b186f4dcb923 makes gr-adapt's master branch compatible with GNU Radio's master branch again.

**Comment by Antoniohopu** [comment]
Hi,

I'm having the same problem but I'm using 3.7 version .... Also, I have installed swig and pybind11 packages but the logs prints:

Warning: failed to XInitThreads()
Traceback (most recent call last):
  File "/media/sf_compartidos/issues1_kaerl/self_interference_cancellation.py", line 338, in <module>
    main()
  File "/media/sf_compartidos/issues1_kaerl/self_interference_cancellation.py", line 326, in main
    tb = top_block_cls()
  File "/media/sf_compartidos/issues1_kaerl/self_interference_cancellation.py", line 234, in __init__
    self.adapt_nlms_filter_xx_0 = adapt.nlms_filter_ff(True, n_taps, gui_nlms_mu, 0, 1, gui_adapt, False, gui_reset)
AttributeError: 'module' object has no attribute 'nlms_filter_ff'

>>> Done

Generating: '/media/sf_compartidos/issues1_kaerl/self_interference_cancellation.py'

Executing: /usr/bin/python2 -u /media/sf_compartidos/issues1_kaerl/self_interference_cancellation.py

Warning: failed to XInitThreads()
Traceback (most recent call last):
  File "/media/sf_compartidos/issues1_kaerl/self_interference_cancellation.py", line 297, in <module>
    main()
  File "/media/sf_compartidos/issues1_kaerl/self_interference_cancellation.py", line 285, in main
    tb = top_block_cls()
  ****File "/media/sf_compartidos/issues1_kaerl/self_interference_cancellation.py", line 194, in __init__
    self.adapt_nlms_filter_xx_0 = adapt.nlms_filter_ff(True, n_taps, gui_nlms_mu, 0, 1, gui_adapt, False, gui_reset)
AttributeError: 'module' object has no attribute 'nlms_filter_ff'****

**Comment by karel** [comment]
@Antoniohopu, are you using both gr-adapt and GNU Radio versions 3.7? If you use GNU Radio 3.7 then please use gr-adapt from branch [maint-3.7](https://github.com/karel/gr-adapt/tree/maint-3.7).
