### ISSUE TITLE
make error: no matching function for call to ‘gr::filter::kernel::fir_filter<float, float, float>::fir_filter(std::vector<float, std::allocator<float> >)’        d_updated(false), d_skip(skip), d_i(0), d_adapt(adapt), d_bypass(bypass), d_reset(false) {                                                                                               ^ In file included from /home/jiang/GNU_Radio_works/gr-adapt-master/lib/lms_filter_ff_impl.h:16:0,                  from /home/jiang/GNU_Radio_works/gr-adapt-master/lib/lms_filter_ff_impl.cc:12:

### ISSUE THREAD

**Issue by dfy888** [karel/gr-adapt#8]
error: no matching function for call to ‘gr::filter::kernel::fir_filter<float, float, float>::fir_filter(std::vector<float, std::allocator<float> >)’
       d_updated(false), d_skip(skip), d_i(0), d_adapt(adapt), d_bypass(bypass), d_reset(false) {
                                                                                              ^
In file included from /home/jiang/GNU_Radio_works/gr-adapt-master/lib/lms_filter_ff_impl.h:16:0,
                 from /home/jiang/GNU_Radio_works/gr-adapt-master/lib/lms_filter_ff_impl.cc:12:

please help me! thanks

**Comment by dfy888** [comment]
my gnuRadio version : 3.9.0    for Ubuntu 18.04

**Comment by karel** [comment]
gr-adapt master branch expects GNU Radio master version. Please try to build gr-adapt from the branch [maint-3.9](https://github.com/karel/gr-adapt/tree/maint-3.9).

**Comment by dfy888** [comment]
> gr-adapt master branch expects GNU Radio master version. Please try to build gr-adapt from the branch [maint-3.9](https://github.com/karel/gr-adapt/tree/maint-3.9).

thanks!
