### ISSUE TITLE
find_package(Gnuradio "3.8" REQUIRED COMPONENTS blocks filter fft)  error

### ISSUE THREAD

**Issue by dfy888** [karel/gr-adapt#9]
CMake Error at CMakeLists.txt:88 (find_package):
  Found package configuration file:

    /usr/lib/cmake/gnuradio/GnuradioConfig.cmake

  but it set Gnuradio_FOUND to FALSE so package "Gnuradio" is considered to
  be NOT FOUND.  Reason given by package:

  The following imported targets are referenced, but are missing: Volk::volk

**Comment by karel** [comment]
Do you have [VOLK](https://github.com/gnuradio/volk) installed? It seems more of a system/dependency problem, than gr-adapt issue. But I am unsure what can cause this (besides not having VOLK installed). You could try asking GNU Radio chat room https://chat.gnuradio.org/.
